// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220530180418_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8_general_ci")
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8");

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("user_email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("userEmail");

                    b.Property<string>("user_pwd")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("userPwd");

                    b.HasKey("user_id");

                    b.ToTable("userTable", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
